.TH TUNEIT 1 "January 27, 2005"
.SH NAME
tuneit \- Simple command line instrument tuner
.SH SYNOPSIS
.B tuneit
.RI [ options ]
.I captureDevice
.SH DESCRIPTION
\fBtuneit\fP Tune-It is a very simple command-line based instrument tuner.
.PP
It uses two different algorithms for pitch detection.  By default,
a simple and fast Schmitt Trigger based algorithm is used to detect
the fundamental frequency of an instrument.  For better and more reliable
results, there is an alternative FFT based algorithm which is much more CPU
intensive.
.SH OPTIONS
\fByatm\fP accepts the following options:
.TP
\fB-f\fP
Use the more CPU intensive FFT based algorithm
.TP
\fB-i\fP
List available input ports and exit
.TP
\fB-a\fP
Use ALSA as the audio transport system
.TP
\fB-j\fP
Use JACK as the audio transport system
.TP
\fB-o\fP
Use OSS as the audio transport system
.TP
\fB-l\fP \fILATENCY\fR
.TP
Measurement window size in 1/N seconds (default is 10)
.TP
\fB-r\fP \fIRATE\fR
.TP
Set desired ALSA sample rate (default is 48000)
.TP
\fB-t\fP \fIHERTZ\fR
.TP
Tune the A note of the scale (default is 440.0)
.SH "SEE ALSO"
.BR jackd (1), amixer (1), mixer(1). 
.SH AUTHORS
Mario Lang <mlang@delysid.org>
.TP
Christian Heckendorf <heckendorfc@gmail.com>
